### ISSUE TITLE
ebdrivererror-disconnected-unable-to-connect-to-renderer

### ISSUE THREAD

**Issue by ubermensh** [marcelmokos/protractor-starter#2]
1. https://stackoverflow.com/questions/46807596/webdrivererror-disconnected-unable-to-connect-to-renderer 
specify another version of chromedriver  (3.33) in package.json
2. I think you should make it MUCH simpler so that other can use it, too much features, too complex structure that takes too much time to understand

**Comment by marcelmokos** [comment]
Thanks for the feedback. 
1. chromedriver and all other dependencies are on latest versions.

yarn upgrade-interactive --latest
yarn upgrade-interactive v1.3.2
success All of your dependencies are up to date.
✨  Done in 0.35s.

2. The only code you need to use is UIComponent.js rest is Page Object pattern which is best practice how to write tests. This is not the only library you should pick up and use. It is a showcase of the Page Object pattern for React application and testing with Protractor framework.

**Comment by marcelmokos** [comment]
Please if you want to help or suggest edits reopen the issue. I am closing the issue for now.
